pipeline{
	agent any
	
	stages{
		stage("DOCKER BUILD"){
			steps{
				echo "BUILD stage"
				sh ''' 
					ls
					pwd
					cd /var/lib/jenkins/workspace/jpl-d-image/Docker/app/maven
					docker build -t bvg98/viji:1.10 .
				'''
			}
		}
		stage("DOCKER PUSH"){
	                 steps{
				sh 'docker image ls'
				sh 'docker push bvg98/viji:1.10'
				echo "Docker image pushed to docker hub successfuly"
			}
		}
		
		stage("Docker-run"){
			steps{
				echo "Running container"
				sh 'docker run -it -d -p 8060:8080 --name viji-tomcat bvg98/viji:1.10'
				sh 'docker ps'
				
			}
		}
	}
}
